# Generated by Django 3.2 on 2022-08-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(db_index=True, max_length=500, unique=True, verbose_name='Адрес'),
        ),
    ]
