# Generated by Django 3.2 on 2022-07-14 03:12

from django.db import migrations


def fill_price(apps, schema_editor):
    OrderElement = apps.get_model('foodcartapp', 'OrderElement')

    order_elements = OrderElement.objects.all()

    for element in order_elements.iterator():
        element.price = element.product.price
        element.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderelement_price'),
    ]

    operations = [
        migrations.RunPython(fill_price),
    ]
