# Generated by Django 3.2 on 2022-07-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_orderelement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('U', 'Необработан'), ('G', 'Собирается'), ('D', 'Доставляется'), ('C', 'Завершён')], default='U', max_length=1, verbose_name='Статус заказа'),
        ),
    ]
