# Generated by Django 3.2 on 2022-07-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20220726_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method_payment',
            field=models.CharField(choices=[('E', 'Электронно'), ('C', 'Наличностью')], db_index=True, default='E', max_length=1, verbose_name='Способ оплаты'),
        ),
    ]
