# Generated by Django 3.2 on 2022-07-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_method_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, 'Необработан'), (1, 'Собирается'), (2, 'Доставляется'), (9, 'Завершён')], db_index=True, default=0, max_length=1, verbose_name='Статус заказа'),
        ),
    ]
