# Generated by Django 3.2 on 2022-08-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_auto_20220816_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='method_payment',
            field=models.CharField(choices=[('E', 'Электронно'), ('C', 'Наличностью')], db_index=True, max_length=1, verbose_name='Способ оплаты'),
        ),
    ]
